language: ruby
rvm:
- 2.1
install:
  - gem install jekyll
  - gem install html-proofer
# script: ./script/cibuild
script: jekyll build && htmlproof ./_site
# branch whitelist
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
